### ISSUE TITLE
Argon2.Verify has no option to set the secret, so custom implementation needed

### ISSUE THREAD

**Issue by Karsten-W** [mheyman/Isopoh.Cryptography.Argon2#10]
Please add some tests that include a secret.

**Comment by mheyman** [comment]
You are right - optional secrets should be easy. I believe the lack of a helper function that takes a secret to be a mistake because that should probably be a fairly common use case - as you realized, custom code was needed if you wanted to use secrets as part of the hash.

I've pushed the updates and version 1.0.8 of [https://www.nuget.org/packages/Isopoh.Cryptography.Argon2](url) has the changes.
