### ISSUE TITLE
Warn users about the size of the nuget installation

### ISSUE THREAD

**Issue by stigzler** [mheyman/Isopoh.Cryptography.Argon2#15]
Your package looked ideal. That is until I grabbed it off nuget and it must have installed about 50 dependencies - looking like all .net core (dev'ing on .net). You should put a warning somewhere on your readme about that. Now I'm left uninstalling loads of dependencies and your library..

**Comment by mheyman** [comment]
Sorry about that. The Nuget.org page pretty clearly states a dependency on NetStandard1.3. This is because standardish cryptographic code requires NetStandard1.3. If I made the code less standard, the lowest the code could be is NetStandard1.2 code but I suspect 1.2 isn't enough smaller than 1.3 to make a difference for you.
