### ISSUE TITLE
Hashing consumes massive amounts of memory after hashing multiple passwords

### ISSUE THREAD

**Issue by JosephEoff** [mheyman/Isopoh.Cryptography.Argon2#25]
After hashing multiple passwords, successive hash operations consume large amounts of RAM.  Allocating the required memory takes a long time, and causes the hash operation to take a long time.

This caused problems in our application.  The operating system itself has to get involved in allocating the required memory.  During the allocation operation, no other processes (or threads) can be carried out on the server.  The result was massive timeouts in the logins and other server operations.

The attached Argon2Test.zip is a complete Visual Studio 2013 solution that illustrates the error.

Start Argon2Test.exe (optionally with a number of hash operations to carry out - default is 200.)

The first few hash operations will be carried out quickly.  Thereafter, depending on how much RAM your system has and the MemoryCost setting, successive hash operations will take longer while the memory allocations are being dealt with.

[Argon2Test.zip](https://github.com/mheyman/Isopoh.Cryptography.Argon2/files/3756743/Argon2Test.zip)

**Comment by mheyman** [comment]
Thanks for the code. the traces below show no increasing memory usage due to iterations. I suspect the issue you had was with some code fixed in the v1.1.7 release where the SecureArray used to try to be helpful by telling you how much memory could have been locked whenever it got a request for memory too large to be locked. This calculation took a long time and consumed as much memory as it could for short amounts of time, and, worse, it seemed to take longer and longer the more times you ran it (at least on Windows 10). That calculation is mostly useful for curiosity's sake and, as of v1.1.7, must be turned on via `SecureArray.ReportMaxLockableOnLockFail`.

MemoryCost=1024 after about 500 iterations:
![image](https://user-images.githubusercontent.com/1261479/88483066-7ddae280-cf33-11ea-9bf8-9af4882031b0.png)
MemoryCost=65536 after about 10 iterations:
![image](https://user-images.githubusercontent.com/1261479/88483139-e3c76a00-cf33-11ea-951a-14c424d85abc.png)
