### ISSUE TITLE
Retrieving version being used

### ISSUE THREAD

**Issue by BigShieldsy** [mheyman/Isopoh.Cryptography.Argon2#38]
Found this package a great asset for my project, however, I am wondering if there was a way for me to get the version number being used during the hashing process?

**Comment by mheyman** [comment]
Hope you got your answer before this because it has been a while since you asked, but...

There is an extension method [`DecodeString()`](https://github.com/mheyman/Isopoh.Cryptography.Argon2/blob/2e58e0da58bf54454caa45732300a78b5c268be6/Isopoh.Cryptography.Argon2/DecodeExtension.cs#L57) on `Argon2Config` so you should be able to do something like:
```csharp
var config = new Argon2Config;
config.DecodeString(justHashedValue, out var hash);
var version = config.Version;
```
Or, you can use a regex - for Argon2, the version is encoded in the hash string. Look for `$v=(\d*)`, the digits in the capture group are the Argon2 version. As a matter of fact, I'm going to wing a regex to pull out all the relevant parts:

`^\$argon2(?<type>i?d?)\$v=(?<version>\d+)\$m=(?<memory>\d+),t=(?<time>\d+),p=(?<parallelism>\d+)(?:,data=(?<data>[A-Za-z0-9/+]+=*))?\$(?<salt>[A-Za-z0-9/+]+=*)\$(?<hash>[A-Za-z0-9/+]+=*)$`

This should give you:
1. hash type: "i", "d", or "id"
1. version: "16" or "19"
1. memory cost
1. time cost
1. parallelism
1. optional base64-encoded associated data
1. base64-encoded salt
1. base64-encoded hash

Caveat: I haven't tested the C# or regex...
